# The Docker image that will be used to build your app
image: python:3.10-alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir public
    - cp ./html/table.html  ./public/index.html
  artifacts:
    paths:
      - public
  only:
    - dev
