# The Docker image that will be used to build your app
image: ubuntu:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - cp ./html/table.html  public/
  artifacts:
    paths:
      - public
  only:
    - dev
