# Simple workflow for deploying static content to GitHub Pages both from main an dev branches
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      
      - name: Copy static site files
        run: |
          mkdir -p gh-pages/${{ github.ref_name == 'main' && echo '.' || echo github.ref_name }}
          cp -r static/* gh-pages/${{ github.ref_name == 'main' && echo '.' || echo github.ref_name }}/
    
      - name: Copy built files
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [ "$BRANCH_NAME" = "main" ]; then
            TARGET_DIR="."
          else
            TARGET_DIR="$BRANCH_NAME"
          fi
          rm -rf gh-pages/$TARGET_DIR
          mkdir -p gh-pages/$TARGET_DIR
          cp -r build/* gh-pages/$TARGET_DIR/

      - name: Commit and push changes
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy ${{ github.ref_name }} branch to GitHub Pages"
          git push origin gh-pages
