# Simple workflow for deploying static content to GitHub Pages both from main an dev branches
name: Deploy to GitHub Pages folder by branch name

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Build (or copy) static site
        run: |
          mkdir site
          cp -r static/* site/

      - name: Checkout main branch into output directory
        uses: actions/checkout@v3
        with:
          ref: main
          path: output

      - name: Copy build into named subfolder
        run: |
          BRANCH=${{ github.ref_name }}
          rm -rf output/$BRANCH
          mkdir -p output/$BRANCH
          cp -r site/* output/$BRANCH/

      - name: Commit and push to main
        run: |
          cd output
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy branch ${{ github.ref_name }} to /${{ github.ref_name }}/"
          git push origin main

